CREATE TABLE IF NOT EXISTS users (
    ID UUID PRIMARY KEY NOT NULL,
    firstName VARCHAR(45) NOT NULL,
    lastName VARCHAR(45) NOT NULL,
    email VARCHAR(60) NOT NULL,
    password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS clothes (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    gender CHAR(10) NOT NULL
        CONSTRAINT CK_clothes_gender CHECK (gender IN ('Meskie', 'Damskie')),
    brand VARCHAR(60) NOT NULL,
    description VARCHAR NOT NULL,
    prize REAL NOT NULL,
    type VARCHAR(60),
    image VARCHAR
);

CREATE TABLE IF NOT EXISTS shoes (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    gender CHAR(10) NOT NULL
        CONSTRAINT CK_shoes_gender CHECK (gender IN ('Meskie', 'Damskie')),
    brand VARCHAR(60) NOT NULL
        CONSTRAINT CK_shoes_brand CHECK (brand IN ('Adidas', 'Reebok', 'Nike', 'Mizuno', 'Asics')),
    description VARCHAR NOT NULL,
    prize REAL NOT NULL,
    image VARCHAR
);

CREATE TABLE IF NOT EXISTS accessories (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    gender CHAR(10) NOT NULL
        CONSTRAINT CK_clothes_gender CHECK (gender IN ('Meskie', 'Damskie', 'Dowolne')),
    brand VARCHAR(60) NOT NULL,
    description VARCHAR NOT NULL,
    prize REAL NOT NULL,
    type VARCHAR(60),
    image VARCHAR
);

CREATE TABLE IF NOT EXISTS supplements (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    brand VARCHAR(60) NOT NULL,
    description VARCHAR NOT NULL,
    prize REAL NOT NULL,
    type VARCHAR(60),
    image VARCHAR
);

INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('Piłka Mikasa V200W', 'Dowolne', 'Mikasa', 'Piłka Mikasa V200W to najnowszy model oficjalnej piłki do siatkówki halowej. Model pojawił się w miejsce zasłużonej piłki Mikasa MVA200.  Mikasa V200W posiada doskonale wyważoną konstrukcję zbudowaną z 18 paneli. Sposób jej wykonania poprawia ruch piłki oraz gwarantuje zawodnikom większą kontrolę podczas gry. Piłka zbudowana została z żółto-niebieskich paneli o perforowanej strukturze. Mikro-wgłębienia zwiększają przyczepność piłki do dłoni. Ponadto żółte panele zostały wykonane w sposób zapobiegający śliskości powierzchni piłki podczas gry. Model V200W będzie uczestniczył w największych imprezach siatkarskich.', '259.99', 'Pilka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/mikasa/160561/pilka-mikasa-v200w-5cf8fed221f5f.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('TIRO TB S', 'Dowolne', 'Adidas', 'Torba sportowa TIRO TB S', '149.99', 'Torba', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/adidas/88623/tiro-tb-s-bs4749-me-5981cd342c599.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('Szalik Polska/ Gramy Razem 2017', 'Dowolne', 'SportowySklep.pl', 'Jesteś kibicem biało-czerwonych? Pasjonujesz się sportem? Mamy coś dla Ciebie! Szalik reprezentacji polskich siatkarzy zaprojektowany specjalnie pod EuroVolley Poland 2017! Z jednej strony szalik zawiera napis "POLSKA" oraz miasta, w których goszczą Mistrzostwa Europy.  Z kolei druga strona wzbogacona została o hasło "Gramy Razem".', '9.99', 'Szalik', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/inne/89824/szalik-me17-me17-szalik-59c4c34f851d0.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('Mizuno Team Kneepad', 'Dowolne', 'Mizuno', 'Ochraniacze siatkarskie Mizuno Team Kneepad zostały zaprojektowane w kolorze białym z czarnym logotypem Mizuno. Nakolanniki sprawdzają sie zaróno w siatkówce, piłce ręcznej, jak i innych dyscyplinach halowych. Cześć ochronna została zbudowana z pięciu paneli zapewniając w ten sposób jeszcze większą ochronę kolana. Nakolanniki zostały wykonane w 50% z poliestru, 20% sztucznego jedwabiu oraz 30% elastyny. Nakolanniki nie ograniczają swobody ruchów podczas gry. W zestawie znajdują się dwa nakolanniki.', '49.99', 'Nakolanniki', 'https://szopex.blob.core.windows.net/shops/media/f1000/2012/mizuno/16648/nakolanniki-siatkarskie-mizuno-team-kneepad-z59ss70201-5d7f6dee29058.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('Oficjalna maskotka biało-czerwonych!', 'Dowolne', 'VolleyShop', 'Oficjalna maskotka orła, która będzie towarzyszyć polskim siatkarzom podczas zbliżającego się sezonu kadrowego. Biało-czerwony orzełek podkreśla przywiązanie do barw narodowych. Niezbędny element każdego fana polskiej siatkówki. Spiesz się, zanim orzełek odfrunie :)', '59.99', 'Maskotka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/inne/88093/maskotka-ora-mistrzostwa-europy-w-pice-siatkowej-mezczyzn-me2017maskotka-5ae1aa337c34f.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('Compressport R2 V2 Ice Blue', 'Dowolne', 'Compressport', 'Opaski COMPRESSPORT® wspomagają krążenie krwi od stóp do serca, dotleniając jednocześnie mięśnie. Opaski doskonale minimalizują wibracje i mikro urazy mięśni zmniejszając ryzyko kontuzji. Po wysiłku wspomagają przepływ krwi przyspieszając regenerację.  Produkt nie pochłania wody, dzięki czemu opaski pozostają lekkie i wygodne przez cały czas użytkowania.', '139.99', 'Opaska kompresyjna', 'https://szopex.blob.core.windows.net/shops/media/f1000/2016/compresspo/71124/opaski-na-ydki-compressport-calf-r2-v2-ice-blue-r2v2-5020-57be979506746.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('Cep Socks For Recovery 2.0 M', 'Dowolne', 'Cep', 'Skarpety kompresyjne Cep Socks For Recovery 2.0 M  zostały zaprojektowane w kolorze czarnym elementami. Materiał, z którego wykonane zostały skarpety kompresyjne zapewnia świetne dopasowanie przy jednoczesnym zachowaniu stabilizacji mięśni oraz stawów. Produkt wpływa na poprawę krążenia. (III) 32 cm - 38 cm, (IV) 39 cm - 44 cm, (V) 45 cm - 50 cm.', '179.99', 'Skarpetki kompresyjne', 'https://szopex.blob.core.windows.net/shops/media/f1000/2016/cep/67351/skarpety-cep-regeneracyjne-czarne-20-555r-58456ffc24bc4.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('Under Armour UA Hustle Backpack', 'Dowolne', 'Under Urmour', 'Plecak sportowy Under Armour UA Hustle', '99.99', 'Plecak', 'https://szopex.blob.core.windows.net/shops/media/f1000/2016/underarm/71343/ua-hustle-backpack-ldwr-gphgphslv-1273274-040-57c411cc8f823.jpg');
INSERT INTO accessories (name, gender, brand, description, prize, type, image) VALUES('adidas 3-Stripes No-Show Socks 3 Pairs Black', 'Dowolne', 'Adidas', 'Skarpetki sportowe adidas, 3 pary.', '26.59', 'Skarpetki', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/adidas/85018/skarpety-3s-per-n-s-hc3p-aa2280-5cbc103f39607.jpg');

INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('Koszulka adidas reprezentacji Polski', 'Meskie', 'Adidas', 'Oryginalna koszulka adidas reprezentacji Polski', '179.99', 'Koszulka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/adidas/89539/koszulka-adidas-pzps-biaa-s98573-b-59e5f18a37b9c.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('Koszulka adidas reprezentacji Polski', 'Damskie', 'Adidas', 'Oficjalna meczowa koszulka reprezentacji polskich siatkarek należąca do aktualnej kolekcji kadrowej. Koszulka została wykonana w białym kolorze z czerwonymi elementami. Jej wyjątkowy charakter podkreśla zamieszczona na lewej piersi flaga Polski. Koszulka jest niezwykle dopasowana, wykonana z materiału gwarantującego wentylację na najwyższym poziomie. Panele boczne, pokryte specjalną siateczką przepuszczającą powietrze, zwiększają komfort podczas wysiłku. Warto podkreślić, iż jako jedyni w Polsce mamy możliwość nanoszenia na koszulki najnowszego wzoru numerów z logotypem "Polskiej Siatkówki" w postaci Orła. Prawdziwa gratka dla największych fanek biało-czerwonych.', '179.99', 'Koszulka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/adidas/89540/koszulka-adidas-pzps-biaa-s98570-b-59e5f84d24696.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('Koszulka adidas MT VB FO MO JR S', 'Meskie', 'Adidas', 'Oficjalna koszulka meczowa reprezentacji polskich siatkarzy z sezonu 2012/13. W tym modelu polscy siatkarze zdobyli złoty medal Ligi Światowej w 2012 w Sofii. Koszulka została zaprojektowana z najwyższej jakości włókien poliestrowych w kolorze białym z czerwonymi elementami. Na przedniej części koszulki widnieją logotypy strategicznych sponsorów kadry biało-czerwonych. Koszulka została wyposażona w system Climacool, który zapewnia doskonałą wentylację podczas użytkowania. Jego zadaniem jest odprowadzenie ciepła oraz potu na zewnątrz.', '179.99', 'Koszulka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2016/adidas/63401/56d44a0aeeb1d-koszulka-adidas-mt-vb-fo-mo-jr-s-o04644-czerwona.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('Koszulka adidas 3 Stripe VBL SS', 'Damskie', 'Adidas', 'Model koszulki siatkarskiej zaprojektowanej z myślą o kadrze polskich siatkarek. W tym modelu polskie siatkarki występowały podczas ME rozgrywanych w Niemczech i Szwajcarii w 2013 r. Nie przegap okazji! Model został wzbogacony o system climacool, który zapewnia wentylację na najwyższym poziomie.', '179.99', 'Koszulka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2012/adidas/16037/0-koszulka-adidas-3-stripe-vbl-ss-o89838.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('adidas Tiro 17', 'Meskie', 'Adidas', ' Spodenki adidas Tiro 17 zaprojektowane zostały w kolorze czerwonym z białymi dodatkami. Wykonane zostały w całości z najwyższej jakości włókien poliestrowych. Przeznaczone są do treningu oraz codziennego użytkowania.', '64.99', 'Spodenki', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/adidas/85030/spodenki-adidas-tiro-17-s99143-5be2d4afe6d2d.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('adidas Entrada 14 Short', 'Meskie', 'Adidas', 'Spodenki sportowe adidas Entrada 14 Short wykonane zostały z najwyższej jakości materiałów zapewniających należyty komfort użytkowania. Materiał z jakiego zostały wykonane to dobrej jakości poliester. Spodenki występują w kolorze białym wraz z czerwonymi elementami.', '29.99', 'Spodenki', 'https://szopex.blob.core.windows.net/shops/media/f1000/2014/adidas/45408/0-szorty-adidas-entrada-14-short-f50636.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('adidas Essentials Solid Full Zip Hoodie', 'Damskie', 'Adidas', 'Bluza damska adidas Essentials Solid Full Zip Hoodie została zaprojektowana w kolorze szarym z czarnymi elementami. Bluza została wykonana z wysokiej jakości materiału przyjemnego w dotyku. Bluza jest przeznaczona do codziennego użytkowania oraz ogólnej aktywności fizycznej.', '159.99', 'Bluza', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/adidas/88083/bluza-ess-solid-fz-hd-s97086-5be58805a965e.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('adidas WO Pant Prime', 'Meskie', 'Adidas', 'Produkt adidas WO Pant Prime to spodnie zaprojektowane w kolorze szarym z małym logtypem addidas w kolorze czarnym. Wykonane zostały z miękkiego materiału przy jednoczesnym wykorzystaniu technologi Climalite, która odpowiedzialna jest za odprowadzenie wilgoci na zewnątrz. Spodnie sportowe sprawdzą się zarówno na treningu, jakii w codziennym użytkowaniu.', '129.99', 'Spodnie', 'https://szopex.blob.core.windows.net/shops/media/f1000/2018/adidas/118008/spodnie-adidas-wo-pant-prime-cd7832-5cc03d0597faf.jpg');
INSERT INTO clothes (name, gender, brand, description, prize, type, image) VALUES ('adidas Black Response Long Tight W', 'Damskie', 'Adidas', 'Model adidas Black Response Long Tight W to damskie legginsy sportowe zaprojektowane w kolorze czarnym. Dodatkowo legginsy są zdobione pomarańczowym paskiem ciągnącym się wzdłuż nogawki. Legginsy zostały wykonane z najwyśzej jakości materiałów syntetycznych. Idealnie sprawują się podczas treningu oraz ogólnej aktywności fizycznej.', '119.99', 'Legginsy', 'https://szopex.blob.core.windows.net/shops/media/f1000/2017/adidas/78009/legginsy-adidas-response-long-tights-w-czarne-b47764-5ca4773456915.jpg');

INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('adidas Dame 6', 'Meskie', 'Adidas', 'Model adidas Dame 6 został zaprojektowany w kolorze czarnym z białymi elementami. Model posiada tekstylną cholwkę dodatkowo wzbogaconą o pleciony system sznurowania. Jego zadaniem jest zapewnienie odpowiedniej stabilizacji podczas gry. Cholewka modelu została wykonana z materiałów, które wspierają proces wentylacji, odprowadzając wilgoć na zewnątrz. Gumowa podeszwa ze wzorem w jodełkę gwarantuje świetną przyczepnośc podczas gry.', '409.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2020/adidas/167127/buty-adidas-dame-6-fu6807-5e26e5c38d6b2.jpg.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('adidas Harden Stepback', 'Meskie', 'Adidas', 'Buty do koszykówki zostały zaprojektowane w kolorze czerwonym z białymi oraz czarnymi elementami. Buty do koszykówki są bardzo lekkie, dzięki czemu zapewniają swobodne poruszanie się podczas gry. Model adidas Harden Stepback posiada specjalną siateczką, która wspiera proces wentylacji, odprowadzająć wilgoć na zewnątrz.', '349.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/adidas/166601/harden-stepback-eg2768-5e09e253aadaa.jpg.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('adidas Harden Vol. 4 "Spitfire"', 'Meskie', 'Adidas', 'Model adidas Harden Vol.4 został wzbogacony w lekką i elastyczną amortyzację opartą na systemie Lightstrike. Dodatkowo buty posiadają specjalną opaskę w śródstopiu dla zapewnienia dodatkowej stabilizacji. Gumowa podeszwa zewnętrzna zapewnia wyjątkową trakcję i przyczepność.', '439.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2020/adidas/166889/buty-adidas-harden-vol-4-ef9928-5e259da1091de.jpg.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('adidas Harden Vol. 4 "Spitfire"', 'Damskie', 'Adidas', 'adidas Alphabounce Trainer', '239.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/adidas/162787/buty-adidas-alphabounce-trainer-m-grey-d96705-5d68f3d317e56.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('adidas Run70S', 'Meskie', 'Adidas', 'adidas Run70S', '179.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/adidas/150140/run70s-cg6140-5d109d7032325.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('adidas Harden Stepback', 'Meskie', 'Adidas', 'Model adidas Harden Stepback to buty, których cholewka została zaprojektowana w oryginalnej kolorystyce. Dodatkowo cholewka modelu została wykonana z oddychającego materiału syntetycznego, który wpływa na komfort podczas gry. Buty cechuje niezwykła lekkość.', '265.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/adidas/165605/buty-adidas-harden-stepback-ef9890-5de4f5b02b402.jpg.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('Under Armour Ua Curry 7', 'Meskie', 'Adidas', 'Under Armour Ua Curry 7', '389.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/under-armour/165230/buty-under-armour-ua-curry-7-3021258-001-5dcbb81e222cf.jpg.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('Mizuno Wave Momentum', 'Meskie', 'Adidas', 'Mizuno Wave Momentum to najnowsza propozycja męskich butów do siatkówki halowej. Model pokryty jest specjalną siateczką, która zapewnia wyjątkową wentylację odprowadzając pot na zewnątrz. Cholewka posiada bezszwową konstrukcję przypominającą skarpetę, która w połączeniu z technologią DynamotionFit daje świetne dopasowanie. Podeszwa wzbogacona o nową piankę odpowiada za miękkość oraz komfort podczas gry. Buty posiadają grubszą niż zwykle wkładkę AP+ która zapewnia stabilność i komfort podczas gry. Podeszwa zewnętrzna pokryta błękitną gumą daje jeszcze większą przyczepność.', '449.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/mizuno/162228/buty-mizuno-wave-momentum-white-beige-v1ga191296-5d67a4b99bf2d.jpg');
INSERT INTO shoes (name, gender, brand, description, prize, image) VALUES ('Mizuno Wave Lightning Z5', 'Meskie', 'Adidas', 'Mizuno Wave Lightning Z5 to najnowsza propozycja obuwia do siatkówki zaprojektowana w kolorze białym z czarnymi elementami.  Buty przeznaczone są dla zawodników poszukujących lekkich oraz dynamicznych butów. Cholewka modelu Mizuno Wave Lightning Z5 została pokryta siateczka zapewniającą wentylację. Stopień amortyzacji oraz lepsze lądowanie udało się uzyskać przy jednoczesnym zachowaniu niskiej wagi buta. Buty posiadają również czujnik Kick-Sensor, który poprawia zwrotność i szybkość.', '419.99', 'https://szopex.blob.core.windows.net/shops/media/f1000/2019/mizuno/155933/buty-mizun0-wave-lightning-z5-white-bl-v1ga190009-5c8b9de063d52.png');

INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Napój energetyczny Squeezy Drink 500G pomarańczowy', 'Squeezy Sports Nutrition', 'Squeezy NAPÓJ ENERGETYCZNY o smaku pomarańczowym, produkt dostępny w postaci proszku w 500 g puszkach. Jedna 500 gramowa puszka proszku zmieszanego z wodą to aż 7,5 litra gotowego napoju do szybkiego uzupełnienia energii.', '49.99', 'Napoj energetyczny', 'https://szopex.blob.core.windows.net/shops/media/f1000/2015/inne/51944/0-napoj-energetyczny-squeezy-drink-500g-pomaranczowy-squeezy-energy-pom.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Żel energetyczny Squeezy 33G - saszetka', 'Squeezy Sports Nutrition', 'SQUEEZY jest pierwszym na świecie dostawcą energii w żelu oraz optymalnym wyborem dla sportowców poszukujących najwyższej wydajności. Wszystkie produkty SQUEEZY są produkowane bez zbędnych składników. Dlatego żele energetyczne Squeezy są lekkostrawne i nie do pobicia w poszukiwaniu maksymalnej wydajności.', '6.99', 'Zel energetyczny', 'https://szopex.blob.core.windows.net/shops/media/f1000/2014/squeezy/49143/zel-energetyczny-squeezy-33g-brzoskwinia-pomarancza-squeezy-zel-brzo-pom-5a9f897d92ee5.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Baton Squeezy Recovery Bar wanilia + czekolada', 'Squeezy Sports Nutrition', 'Squeezy BATON REGENERACYJNY w czekoladzie o smaku waniliowym (50 g) to idealna przekąska po intensywnym treningu czy zawodach. Baton wspomaga układ odpornościowy i pozwala zmniejszyć ryzyko wystąpienia infekcji po zajęciach sportowych. Zawiera 30% białka niezbędnego do regeneracji mięśni oraz 44% węglowodanów uzupełniających zbiorniki glikogenu.', '9.99', 'Baton', 'https://szopex.blob.core.windows.net/shops/media/f1000/2014/inne/46045/0-baton-wanilia-czekolada-squeezy-recovery-bar.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Suplement Powergym Isopower 600 G', 'Power GYM', 'Napój izotoniczny uzupełniający witaminy i minerały, zapewniający maksymalną wydajność, oraz zapobiegający skurczom mięśni.', '109.99', 'Napoj izotoniczny', 'https://szopex.blob.core.windows.net/shops/media/f1000/2014/powergym/40968/0-suplement-powergym-isopower-600g-203668.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Żel Energetyczny Squeezy 33g pomidorowy - saszetka', 'Squeezy Sports Nutrition', 'Squeezy przedstawia jedyny na świecie lekko słonawy żel o smaku pomidorów. Dzięsięciokrotna zawartość sodu i potasu minimalizuje ryzyko powstawania skurczy podczas wysiłku. Energetyczny żel pomidorowy to idealna alternatywa dla słodkich żeli. Warto sięgnąć po zdrowszą wersję żelu energetycznego!', '6.99', 'Zel energetyczny', 'https://szopex.blob.core.windows.net/shops/media/f1000/2014/inne/40840/0-zel-energetyczny-squeezy-33g-pomidorowy-squeezy-zel-pomidor.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Saszetka POWERGYM Enegry Plus', 'Power GYM', 'ENERGYPLUS to skoncentrowane źródło węglowodanów o niskim indeksie glikemicznym. Spożywając ENERGYPLUS przed rozpoczęciem ćwiczeń, uzupełnimy zapasy glikogenu, a tym samym będziemy mieli większą ilość „paliwa”, dzięki czemu zwiększy się nasza wydolność i zużyjemy więcej tłuszczu. Jest to możliwe, ponieważ ENERGYPLUS dostarcza nam węglowodanów o niskim indeksie glikemicznym. Ponadto ENERGY PLUS zawiera aminokwasy takie jak, tauryna, L-glutamina, L-arginina i L-tyrozyna, które poprawiają spalanie tłuszczu podczas wysiłku fizycznego (oszczędzając jednocześnie nasze zapasy glikogenu), zwiększają naszą wytrzymałość i redukują zmęczenie.', '13.99', 'Przedtreningowka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2013/powergym/24759/0-saszetka-powergym-enegry-plus-pg-energy-sasz.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Saszetka POWERGYM IsoPower', 'Power GYM', 'ISOPOWER przeznaczony jest do sportu zawodowego. Zawiera on odpowiednie ilości sodu i potasu, które okazały się skuteczne w badaniach naukowych w celu odpowiedniego nawodnienia organizmu.', '8.99', 'Napoj izotoniczny', 'https://szopex.blob.core.windows.net/shops/media/f1000/2013/powergym/24760/saszetka-powergym-isopower-pg-iso-sasz-5ab205dd220b3.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('Agisko Gel Servings Box Citrus - saszetka', 'Agisko', 'Agisko Gel Servings Box Citrus - saszetka. Składniki: maltoza, polisacharydy, woda, maltorioza, mct, wyciąg z owoców, lecytyna sojowa, glukoza, d-ryboza, aromat, kwas cytrynowy, sorbinian potasu. Instrukcja: dla lepszego rezultatu AGISKO ŻEL powinien być stosowany na 15-20 minut przed wysiłkiem i kolejno jedno opakowanie 37g co 60 minut wysiłku', '7.99', 'Zel energetyczny', 'https://szopex.blob.core.windows.net/shops/media/f1000/2014/agisko/40485/agisko-gel-servings-box-citrus-saszetka-179049-5ab20334baa92.jpg');
INSERT INTO supplements (name, brand, description, prize, type, image) VALUES ('PowerGym Energy Plus 1100 G', 'Power GYM', 'ENERGYPLUS to skoncentrowane źródło węglowodanów o niskim indeksie glikemicznym. Spożywając ENERGYPLUS przed rozpoczęciem ćwiczeń, uzupełnimy zapasy glikogenu, a tym samym będziemy mieli większą ilość „paliwa”, dzięki czemu zwiększy się nasza wydolność i zużyjemy więcej tłuszczu. Jest to możliwe, ponieważ ENERGYPLUS dostarcza nam węglowodanów o niskim indeksie glikemicznym. Ponadto ENERGY PLUS zawiera aminokwasy takie jak, tauryna, L-glutamina, L-arginina i L-tyrozyna, które poprawiają spalanie tłuszczu podczas wysiłku fizycznego (oszczędzając jednocześnie nasze zapasy glikogenu), zwiększają naszą wytrzymałość i redukują zmęczenie.', '154.99', 'Przedtreningowka', 'https://szopex.blob.core.windows.net/shops/media/f1000/2014/powergym/44347/0-powergym-energy-plus-1100g-215988.jpg');