-- Buty
-- męskie
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Harden Stepback 2', 'Męskie', 'Adidas', 'Buty siatkarskie adidas Harden Stepback 2', 379.99, 'https://blob.sxv.pl/shops/media/f1000/2020/adidas/184893/harden-stepback-2-cblack-silvmt-ftwwht-fz1384-601d1beec2c5e.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Under Armour Embiid One "Light Blue"', 'Męskie', 'Under Armour', 'Buty siatkarskie Under Armour Embiid One "Light Blue"', 539.99, 'https://blob.sxv.pl/shops/media/f1000/2020/under-armour/188488/ua-embiid-1-3023086-402-602ccc6bc1fa4.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Under Armour Embiid One "Brotherly Love"', 'Męskie', 'Under Armour', 'Buty siatkarskie Under Armour Embiid One "Brotherly Love"', 539.99, 'https://blob.sxv.pl/shops/media/f1000/2020/under-armour/188487/ua-embiid-1-3023086-107-602ccc4a38b85.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Under Armour Embiid One "Origin"', 'Męskie', 'Under Armour', 'Buty siatkarskie Under Armour Embiid One "Origin"', 539.99, 'https://blob.sxv.pl/shops/media/f1000/2020/under-armour/172553/ua-embiid-1-3023086-001-600153ef32144.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Sky Elite FF MT "Tokyo"', 'Męskie', 'Asics', 'Model asics Sky Elite FF "Tokyo" został zaptojektowany w kolorze czerwonym w wersji za kostkę. Buty asics Sky Elite FF "Tokyo" zostały wzbogacone o rewolucyjny system FlyteFoam ™opierający sie na miękkiej i sprężystej piance, która gwarantuje odpowiednią dynamikę podczas gry. Chloweka modelu została pokryta perforowanym materiałem, który odpowiada za wentylację, odprowadzając wilgoć na zewnątrz. Zastosowany w podeszwie system Twistruss System® usztywnia ją w centralnej części stabilizując jednocześnie stopę podczas kontaktu butów z podłożem. Buty posiadają wkładki żelowe, które znajdują się w przedniej i tylnej części zwiększając komfort oraz bezpieczeństwo podczas gry.', 669.99, 'https://blob.sxv.pl/shops/media/f1000/2021/asics/188962/buty-asics-sky-elite-ff-mt-tokyo-sunrise-red-eclipse-black-1051a056-701-5ff869a8ea192.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Pro Boost Low', 'Męskie', 'Adidas', 'Buty siatkarskie Adidas Pro Boost Low', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/adidas/184968/pro-boost-gca-low-cblack-cblack-cblack-g58681-600abcceb8c30.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Nike Hyperspeed Court (CI2964-010)', 'Męskie', 'Nike', 'Buty siatkarskie Nike Hyperspeed Court (CI2964-010)', 239.99, 'https://blob.sxv.pl/shops/media/f1000/2020/nike/181403/buty-nike-nike-hyperspeed-court-black-white-ci2964-010-5fe1c1620b0d0.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Pro Boost Low Shoes', 'Męskie', 'Adidas', 'Buty siatkarskie adidas Pro Boost Low Shoes', 359.99, 'https://blob.sxv.pl/shops/media/f1000/2020/adidas/178934/buty-adidas-pro-boost-low-fw9503-5f7429d6e017b.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Voltage', 'Męskie', 'Mizuno', 'Buty siatkarskie Mizuno Wave Voltage', 349.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/178464/buty-mizuno-wave-voltage-reflex-blue-c-white-diva-pink-v1ga196020-5f61b776806d9.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Momentum', 'Męskie', 'Mizuno', 'Mizuno Wave Momentum to najnowsza propozycja męskich butów do siatkówki halowej. Buty zostały zaprojektowane w kolorze czarnym. Model pokryty jest specjalną siateczką, która zapewnia wyjątkową wentylację. Cholewka posiada bezszwową konstrukcję przypominającą skarpetę, która w połączeniu z technologią DynamotionFit gwarantuje niesamowite dopasowanie. Podeszwa wzbogacona o nową piankę odpowiada za miękkość oraz komfort podczas gry. Podeszwa zewnętrzna pokryta błękitną gumą daje jeszcze większą przyczepność.', 499.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/178473/buty-mizuno-wave-momentum-black-white-safety-yellow-v1ga191245-5f61b6526f4ec.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Lightning Neo', 'Męskie', 'Mizuno', 'Mizuno Wave Lightning Neo to najnowsza odsłona butów do siatkówki japońskiego producenta. Model występuje w wersji za kostkę i przeznaczony jest dla osób poszukujących lekkich, dynamicznych butów siatkarskich. Buty wyróżnia rewolucyjna konstrukcja opierająca się na specjalnej, elastycznej "skarpecie" wbudowanej w cholewkę. Jej zadaniem jest zapewnienie doskonałej stabilizacji oraz dopasowania. Zastosowany materiał amortyzujący jest lżejszy oraz idealnie absorbuje wstrząsy powstałe podczas lądowania.', 559.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/178470/buty-mizuno-wave-lightning-neo-reflex-blue-c-silver-diva-pink-v1ga200220-5f61bcd60b344.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Lightning Z6', 'Męskie', 'Mizuno', 'Mizuno Wave Lightning Z6 to kolejna odsłona modelu japońskiego producenta obuwia do siatkówki. Model przeznaczony jest dla osób poszukujących lekkich, dynamicznych butów siatkarskich. Idealny model dla ofensywnie nastawionych zawodników. Model Mizuno Wave Lightning Z6 posiada wzmocnioną cholewką, która gwarantuje bezkonkurencyjne dopasowanie oraz czucie w trakcie gry. Zastosowany materiał amortyzujący jest lżejszy oraz idealnie absorbuje wstrząsy powstałe podczas lądowania.  Model posiada czujnik kick-sensor pod palcami, który poprawia szybkość i zwrotność.', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/178474/buty-mizuno-wave-lightning-z6-white-black-diva-blue-v1ga200046-5fa1498b8139d.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Nike React Hyperset', 'Męskie', 'Nike', 'Nike React Hyperset to najnowszy model do siatkówki ze stajni Nike. Cholewka modelu została zaprojektowana w kolorze białym z czarnymi elementami. Ponadto cholewka wykonana jest ze specjalnej siateczki, której zadaniem jest odprowadzenie wilgoci na zewnątrz. Całość wyróżnia specjalny pasek otaczający cholewkę zapewniąc doskonałą stabilizację. Za amortyzację butów odpowiada miękka pianka Nike React, która amortyzuje wstrząsy powstałe podczas gry.  Męskie buty do siatkówki Nike React Hyperset łączą w sobie niezwykłą przyczepność, dynamiczną amortyzację oraz niesamowity komfort.', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/nike/178410/buty-nike-react-hyperset-ci2955-100-5f61e25ead395.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Netburner Ballistic FF 2', 'Męskie', 'Asics', 'Buty asics Netburner Ballistic zostały zaprojektowane w wersji przed kostkę, w kolorze czarnym z czerwonymi elementami. Cholewka butów pokryta jest specjalna siateczką, która odprowadza wilgoć na zewnątrz. Zastosowana w podeszwie środkowej technologia FLYTEFOAM™ zapewnia dodatkowe odbicie i uczucie lekkości za każdym razem, gdy ruszasz do piłki. Podeszwa N.C. RUBBER™ gwarantuje należytą przyczepność, a wkładka EVA zwiększa komfort podczas gry.', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/asics/177906/buty-asics-netburner-ballistic-ff-2-l-e-1051a060-010-5f44f3979476d.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Lightning Z6', 'Męskie', 'Mizuno', 'Mizuno Wave Lightning Z6 to kolejna odsłona modelu japońskiego producenta sprzętu sportowego. Model przeznaczony jest dla osób poszukujących lekkich, dynamicznych butów siatkarskich. Idealny model dla ofensywnie nastawionych zawodników. Model Mizuno Wave Lightning Z6 posiada wzmocnioną cholewką, która gwarantuje bezkonkurencyjne dopasowanie oraz czucie w trakcie gry. Zastosowany materiał amortyzujący jest lżejszy oraz idealnie absorbuje wstrząsy powstałe podczas lądowania.  Model posiada czujnik kick-sensor pod palcami, który poprawia szybkość i zwrotność.', 419.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/169945/buty-mizuno-wave-wave-lightning-z6-black-white-orange-clown-fish-v1ga200053-5f4d244544e20.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Netburner Ballistic FF 2 MT', 'Męskie', 'Asics', 'Buty asics Netburner Ballistic zostały wykonane w wersji za kostkę minimalizując w ten sposób ryzyko odniesienia kontuzji skręcenia stawu skokowego. Model został zaprojektowany w kolorze czarnym z czerwonymi elementami. Cholewka butów pokryta jest specjalna siateczką, która odprowadza wilgoć na zewnątrz. Zastosowana w podeszwie środkowej technologia FLYTEFOAM™ zapewnia dodatkowe odbicie i uczucie lekkości za każdym razem, gdy ruszasz do piłki. Podeszwa N.C. RUBBER™ gwarantuje należytą przyczepność, a wkładka EVA zwiększa komfort podczas gry.', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/asics/177589/buty-asics-netburner-ballistic-ff-mt-2-black-carrier-grey-1051a042-001-5f2d09e6a7ab3.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Voltage', 'Męskie', 'Mizuno', 'Buty siatkarskie Mizuno Wave Voltage', 349.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/169864/buty-mizuno-wave-voltage-wht-trueb-v1ga196021-5ec437a83e9de.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Miuzno Wave Momentum', 'Męskie', 'Mizuno', 'Mizuno Wave Momentum to najnowsza propozycja męskich butów do siatkówki halowej. Buty zostały zaprojektowane w kolorze pomarańczowym z czarnymi elementami. Model pokryty jest specjalną siateczką, która zapewnia wyjątkową wentylację odprowadzając pot na zewnątrz. Cholewka posiada bezszwową konstrukcję przypominającą skarpetę, która w połączeniu z technologią DynamotionFit gwarantuje niesamowite dopasowanie. Podeszwa wzbogacona o nową piankę odpowiada za miękkość oraz komfort podczas gry. Buty posiadają grubszą niż zwykle wkładkę AP+ która zapewnia stabilność i komfort podczas gry. Podeszwa zewnętrzna pokryta błękitną gumą daje jeszcze większą przyczepność.', 429.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/168875/buty-mizuno-wave-momentum-orangeclow-v1ga191254-5e82d0ee0c7db.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Harden Vol. 4', 'Męskie', 'Adidas', 'Model adidas Harden Vol.4 został wzbogacony w lekką i elastyczną amortyzację opartą na systemie Lightstrike. Dodatkowo buty posiadają specjalną opaskę w śródstopiu dla zapewnienia dodatkowej stabilizacji. Gumowa podeszwa zewnętrzna zapewnia wyjątkową trakcję i przyczepność.', 439.99, 'https://blob.sxv.pl/shops/media/f1000/2020/adidas/168890/buty-adidas-harden-vol-4-fv4151-5e74a47d7b033.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Lightning Z5', 'Męskie', 'Mizuno', 'Mizuno Wave Lightning Z5 to najnowszy model butów przed kostkę do uprawiania siatkówki halowej. Buty zostały zaprojektowane w delikatnym kolorze niebieskim z białymi elementami. Buty przeznaczone są dla wymagających zawodników poszukujących lekkich oraz dynamicznych butów. Cholewka modelu Mizuno Wave Lightning Z4 została stworzona ze specjalnej siateczki, która odprowadza wilgoć na zewnątrz. Stopień amortyzacji oraz lepsze lądowanie udało się uzyskać przy jednoczesnym zachowaniu niskiej wagi buta. Buty posiadają również czujnik Kick-Sensor, który poprawia zwrotność i szybkość.', 429.99, 'https://blob.sxv.pl/shops/media/f1000/2019/mizuno/162230/buty-mizun0-wave-lightning-z5-indiantan-wht-sheepskin-v1ga190096-5d84ae56d2492.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Pro Bounce', 'Męskie', 'Adidas', 'Buty siatkarskie adidas Pro Bounce', 309.99, 'https://blob.sxv.pl/shops/media/f1000/2020/adidas/168010/pro-bounce-2019-low-cblack-ftwwht-scarle-eg2818-5e46a35bda9ff.jpg.jpg');
-- damskie
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Luminous', 'Damskie', 'Mizuno', 'Damskie buty do siatkówki Mizuno Wave Luminous to najnowsza propozycja damskiego obuwia siatkarskiego. Buty zostały zaprojektwoane w kolorze pomarańczowym. Cholewka posiada specjalna siateczkę, która bierze udział w wentylacji powietrza, odprowadzając wilgoć na zewnątrz. Buty przeznaczone są dla siatkarzy, którzy cenią sobie niezwykły komfort oraz stabilność. Cholewka Mizuno Wave Luminous posiada "skarpetkową" konstrukcję, za sprawą czego model cechuje się niesamowitym dopasowaniem. Wkładka z gęstej pianki EVA oraz płytka Wave gwarantują świetną amortyzację.', 399.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/178465/buty-mizuno-wave-luminous-living-coral-snow-white-v1gc182059-5f61be18d9551.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Sky Elite FF', 'Damskie', 'Asics', 'Model asics Sky Elite FF wchodzi w skład najnowszej kolekcji butów do siatkówki przeznaczonej dla zaawansowanych siatkarek. Buty zostały wykonane z materiału syntetycznego. Cholewka butów pokryta została dodatkowo specjalną siateczką, której zadaniem jest odprowadzenie wilgoci na zewnątrz. Buty bazują na rewolucyjnym systemie FlyteFoam opierającym się na wyjątkowo miękkiej i sprężystej piance zapewniającej dodatkową dynamikę. Całość dopełnia niepozostawiająca śladów podeszwa zewnętrzna, która gwarantuje świetną przyczepność podczas gry. ', 399.99, 'https://blob.sxv.pl/shops/media/f1000/2019/asics/163991/buty-asics-sky-elite-ff-1052a024-100-5d6ccfba3b46c.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Luminous', 'Damskie', 'Mizuno', 'Damskie buty do siatkówki Mizuno Wave Luminous to najnowsza propozycja damskiego obuwia siatkarskiego. Model został zaprojektowany w kolorze granatowym z białymi elementami. Cholewka posiada specjalna siateczkę, która bierze udział w wentylacji powietrza, odprowadzając wilgoć na zewnątrz. Buty przeznaczone są dla siatkarzy, którzy cenią sobie niezwykły komfort oraz stabilność. Cholewka Mizuno Wave Luminous posiada "skarpetkową" konstrukcję, za sprawą czego model cechuje się niesamowitym dopasowaniem. Wkładka z gęstej pianki EVA oraz płytka Wave gwarantują świetną amortyzację.', 459.99, 'https://blob.sxv.pl/shops/media/f1000/2019/mizuno/164249/buty-mizuno-wave-luminous-astral-aura-v1gc182015-5d760395e01ce.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Thunder Blade 2', 'Damskie', 'Mizuno', 'Damskie buty do siatkówki Mizuno Thunder Blade zaprojektowane zostały w kolorze fioletowym z białymi oraz różowymi szczegółami. Cholewka wykonana jest z materiału syntetycznego, który zapewni Tobie najwyższy komfort podczas gry. Buty posiadają również specjalną siateczkę, która odprowadza na zewnątrz wilgoć i pot. W butach zastosowano wkładkę z materiału ap+, której zadaniem jest zapewnienie niesamowitej amortyzacji. Podeszwa została wykonana z niebrudzącej gumy doskonale "trzymającej się" nawet mokrego parkietu. ', 309.99, 'https://blob.sxv.pl/shops/media/f1000/2019/mizuno/162235/buty-mizuno-wavethunder-blade-2-v1gc197002-5d6798250a350.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Netburner Ballistic FF MT', 'Damskie', 'Asics', 'Model asics Netburner Ballistic FF MT należy do najnowszej kolekcji butów do siatkówki marki asics. Buty zostały zaprojektowane w kolorze czarnym z różowymi elementami. Model należy do najbardziej zaawansowanych butów siatkarskich, które spełnią oczekiwania najbardziej wymagających zawodniczek. Buty posiadają szereg technologii, które gwarantują wysoki komfort użytkowania oraz minimalizują ryzyko doznania urazu. Buty posiadają specjalną piankę FlyteFoam bazującą na organicznych włóknach, które gwarantują świetne odbicie oraz amortyzację. Zastosowany system Rearfoot and Forefoot Gel maksymalnie amortyzuje wstrząsy powstałe podczas biegu. Buty posiadają wymienną wkładkę dostosowującą się do stopy. Podeszwa zewnętrzna butów asics Netburner Ballistic FF wykonana została ze specjalnego tworzywa chroniącego przed poślizgiem na mokrej nawierzchni.', 439.99, 'https://blob.sxv.pl/shops/media/f1000/2019/asics/160765/buty-asics-netburner-ballistic-ff-mt-black-laser-pink-1052a001-001-5cfe3805e7855.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Momentum', 'Damskie', 'Mizuno', 'Mizuno Wave Momentum to najnowsza propozycja damskich butów do siatkówki halowej. Buty zostały zaprojektowane w kolorze białym z czarno-szarymi elementami. Model pokryty jest specjalną siateczką, która zapewnia wyjątkową wentylację odprowadzając pot na zewnątrz. Cholewka posiada bezszwową konstrukcję przypominającą skarpetę, która w połączeniu z technologią DynamotionFit gwarantuje  niesamowite dopasowanie. Podeszwa wzbogacona o nową piankę odpowiada za miękkość oraz komfort podczas gry. Buty posiadają grubszą niż zwykle wkładkę AP+ która zapewnia stabilność i komfort podczas gry. Podeszwa zewnętrzna pokryta błękitną gumą daje jeszcze większą przyczepność.', 499.99, 'https://blob.sxv.pl/shops/media/f1000/2019/mizuno/155049/buty-mizuno-wave-momentum-white-black-clearwater-v1gc191210-5c63c7e3b0a84.png');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Volley Elite FF', 'Damskie', 'Asics', 'Buty asics volley Elite FF MT to najnowsza propozycja obuwia do siatkówki halowej skierowana dla zawodniczek poszukujących dynamicznych oraz lekkich butów. Podeszwa środkowa posiada innowacyjną piankę FlyteFoam, która w połączeniu z systemem GEL zapewnia niesamowitą amortyzację oraz lekkość. Cholewka modelu asics Volley Elite FF została wykonana z włókien syntetycznych. Dzięki temu rozwiązaniu buty lepiej odprowadzają wilgoć na zewnątrz. W miejscach najbardziej narażonych na uszkodzenia, buty zostały dodatkowo wzmocnione. Podeszwa zewnętrzna wykonana została z materiałów, które zapewniają wysoką przyczepność nawet na mokrej powierzchni.', 379.99, 'https://blob.sxv.pl/shops/media/f1000/2018/asics/103955/buty-asics-volley-elite-ff-b751n-400-5b891ec58e497.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Netburner Ballistic FF MT', 'Damskie', 'Asics', 'Model asics Gel-Netburner FF MT to najnowsza edycja z tej serii przeznaczona dla zawodniczek poszukujących lekkich oraz dynamicznych butów do siatkówki halowej. Buty zostały zaprojektowane w wersji za kostkę dzięki czemu minimalizują ryzyko odniesienia kontuzji. Cholewka modelu została wykonana z materiału syntetycznego oraz przewiewnej tkaniny, która pozwoli zachować najwyższy komfort podczas gry. Buty posiadają rewelacyjną piankę, która dopasowuje się do pięty i ścięgna achillesa minimalizując ryzyko powstania otarć. Podeszwa zewnętrzna pokryta jest specjalna gumą, która zapewnia przyczepność na śliskich i mokrych nawierzchniach.', 349.99, 'https://blob.sxv.pl/shops/media/f1000/2018/asics/103945/buty-asics-netburner-ballistic-ff-mt-1052a001-400-5ba2087aa5e12.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Mizuno Wave Lightning Z6', 'Damskie', 'Mizuno', 'Mizuno Wave Lightning Z6 to kolejna odsłona modelu stworzona z myślą o zawodniczkach poszukujących lekkich, dynamicznych butów siatkarskich. Model Mizuno Wave Lightning Z6 posiada wzmocnioną cholewką, która gwarantuje bezkonkurencyjne dopasowanie oraz czucie w trakcie gry. Zastosowany materiał amortyzujący jest lżejszy oraz idealnie absorbuje wstrząsy powstałe podczas lądowania.  Model posiada czujnik kick-sensor pod palcami, który poprawia szybkość i zwrotność.', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/mizuno/178475/buty-mizuno-wave-lightning-z6-della-robbia-blue-white-2768-c-v1gc200029-5f61be9bcd7c6.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Asics Sky Elite FF MT', 'Damskie', 'Asics', 'Model asics Sky Elite FF MT został zaptojektowany w granatowym kolorze z białymi elementami. Chloweka modelu została pokryta perforowanym materiałem, który odpowiada za wentylację, odprowadzając wilgoć na zewnątrz. Model został wzbogacony o szereg technologii, które gwarantują bezpieczeństwo i najwyższy komfort podczas gry. Podeszwa środkowa wykonana w technologii Fluidride, za sprawą lekkich włókien, zapewnia świetną amortyzację pod stopami. Technologia Trusstic System gwarantuje pełną kontrolę podczas skręcania, a technologia GEL umieszczona w tylniej części zapewnia amortyzację. Model posiada amortyzacyjną wkładkę, która skutecznie odprowadza wilgoć oraz pot podczas najbardziej intensywnych meczów.', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/asics/177248/buty-asics-sky-elite-ff-mt-1052a023-400-5f293b804a6ca.jpg');
-- junior
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Harden Vol.5', 'Junior', 'Adidas', 'Buty siaktarskie dziecięce adidas Harden Vol.5', 449.99, 'https://blob.sxv.pl/shops/media/f1000/2020/adidas/184482/harden-vol-5-j-cblack-ftwwht-royblu-fx8666-600699f3699db.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Converse Chuck Taylor All Star Black', 'Junior', 'Converse', 'Buty dziecięce Converse Chuck Taylor All Star Black', 269.99, 'https://blob.sxv.pl/shops/media/f1000/2014/converse/42352/buty-converse-chuck-taylor-all-star-m9166-5adf15be9913a.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Derrick Rose 773 junior', 'Junior', 'Adidas', 'Buty dziecięce adidas Derrick Rose 773 junior', 249.99, 'https://blob.sxv.pl/shops/media/wbsquare2/2020/adidas/184896/d-rose-773-2020-j-cblack-ftwwht-cblack-fz1402-601d2fd40f996.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas D.O.N Issue #2', 'Junior', 'Adidas', 'Buty dziecięce adidas D.O.N Issue #2', 216.99, 'https://blob.sxv.pl/shops/media/wbsquare2/2020/adidas/178935/buty-adidas-d-o-n-issue-2-j-fw8752-5f87fad70bf1e.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Under Armour Curry 7 (GS)', 'Junior', 'Under Armour', 'Buty dziecięce Under Armour Curry 7 (GS)', 219.99, 'https://blob.sxv.pl/shops/media/f1000/2019/under-armour/165107/buty-under-armour-ua-gs-curry-7-3022113-100-5e283fca89644.jpg.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Under Armour Lockdown 4 (GS)', 'Junior', 'Under Armour', 'Buty dziecięce Under Armour Lockdown 4 (GS)', 129.99, 'https://blob.sxv.pl/shops/media/wbsquare2/2020/under-armour/170534/buty-under-armour-ua-gs-lockdown-4-niebieski-3022123-403-5f7da7a7be7c2.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Adidas Harden Vol.4 J x Star Wars Lightsaber', 'Junior', 'Adidas', 'Model adidas Harden Vol.4 J x Star Wars Lightsaber wchodzą w skład limitowanej kolekcji. Cholekwa modelu została zaprojektowana w kolorze czarnym z fioletowymi elementami. Model gwarantuje świetną przyczepność i komfort podczas gry. Buty zostały zostały wzbogacone o ultralekką i elastyczną amortyzację umieszczoną w podeszwie środkowej. Gumowa podeszwa zapewnia świetną przyczepność podczas meczu.', 349.99, 'https://blob.sxv.pl/shops/media/f1000/2019/adidas/160314/harden-vol-4-j-s-cblack-silvmt-actpur-ef2080-5dc3e6e30d60b.jpg.jpg');
INSERT INTO shoes(name, gender, brand, description, prize, image) values('Under Armour Curry 7 (GS)', 'Junior', 'Under Armour', 'Buty dziecięce Under Armour Curry 7 (GS)', 219.99, 'https://blob.sxv.pl/shops/media/f1000/2019/under-armour/165827/buty-under-armour-ua-gs-curry-7-3022113-405-5df9f87f4f799.jpg.jpg');

-- Odzież
-- męska
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Koszulka adidas MT VB FO MO JR S', 'Męskie', 'Adidas', 'Oficjalna koszulka meczowa reprezentacji polskich siatkarzy z sezonu 2012/13. W tym modelu polscy siatkarze zdobyli złoty medal Ligi Światowej w 2012 w Sofii. Koszulka została zaprojektowana z najwyższej jakości włókien poliestrowych w kolorze białym z czerwonymi elementami. Na przedniej części koszulki widnieją logotypy strategicznych sponsorów kadry biało-czerwonych. Koszulka została wyposażona w system Climacool, który zapewnia doskonałą wentylację podczas użytkowania. Jego zadaniem jest odprowadzenie ciepła oraz potu na zewnątrz.', 179.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2016/adidas/63401/56d44a0aeeb1d-koszulka-adidas-mt-vb-fo-mo-jr-s-o04644-czerwona.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Koszulka adidas MT VB FO MO JR S', 'Męskie', 'Adidas', 'Oficjalna koszulka meczowa reprezentacji polskich siatkarzy z sezonu 2012/13. W tym modelu polscy siatkarze zdobyli złoty medal Ligi Światowej w 2012 w Sofii. Koszulka została zaprojektowana z najwyższej jakości włókien poliestrowych w kolorze białym z czerwonymi elementami. Na przedniej części koszulki widnieją logotypy strategicznych sponsorów kadry biało-czerwonych. Koszulka została wyposażona w system Climacool, który zapewnia doskonałą wentylację podczas użytkowania. Jego zadaniem jest odprowadzenie ciepła oraz potu na zewnątrz.', 179.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2016/adidas/63400/56d44a0ad5bb4-koszulka-adidas-mt-vb-fo-mo-jr-s-o04644-biala.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Koszulka adidas Polo M', 'Męskie', 'Adidas', 'Oficjalny model koszulki kadry polskich siatkarzy z Mistrzostw Europy w Turcji z 2009 r. Podczas tego turnieju polscy siatkarze zdobyli złoty medal ME, z kolei Piotr Gruszka został uznany MVP całego turnieju. Ekipa dowodzona wówczas przez Daniela Castellaniego bez porażki przebrnęła przez cały turniej zwyciężając w finale z drużyną Francji 3:1. Koszulka została zaprojektowana w kolorze białym z czerwonymi elementami. Na przodzie koszulki znajduje się logotyp sponsora polskich siatkarzy. Produkt posiada wbudowany system CLIMA gwarantujący prawidłowe odprowadzanie wilgoci na zewnątrz. Dodatkowo rękawy i boki koszulki stworzone są ze specjalnego materiału zwiększającego przewiewność.', 99.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2009/adidas/1179/0-koszulka-adidas-polo-m-e86465.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Polo adidas Tiro 17', 'Męskie', 'Adidas', 'Koszulka Polo adidas Tiro 17 została wykonana z połączenia najwyższej jakości materiałów syntetycznych oraz tekstylnych. Koszulka przeznaczona jest do codziennego użytkowania oraz do ogólnej aktywności fizycznej.', 87.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2017/adidas/78424/koszulka-polo-adidas-tiro-17-bq2680-5be409f97a114.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Regista 18', 'Męskie', 'Adidas', 'Spodenki adidas Regista 18 zaprojektowane zostały w kolorze czerwonym z białymi elementami. Wykonane zostały w całości z najwyższej jakości włókien poliestrowych. Przeznaczone są do treningu oraz codziennego użytkowania.', 99.99, 'Spodenki', 'https://blob.sxv.pl/shops/media/f1000/2018/adidas/95723/spodenki-adidas-regista-18-cw2019-5be2d6f0b982f.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Entrada 14 Short', 'Męskie', 'Adidas', 'Spodenki sportowe adidas Entrada 14 Short wykonane zostały z najwyższej jakości materiałów zapewniających należyty komfort użytkowania. Materiał z jakiego zostały wykonane to dobrej jakości poliester. Spodenki występują w kolorze białym wraz z czerwonymi elementami.', 36.99, 'Spodenki', 'https://blob.sxv.pl/shops/media/f1000/2014/adidas/45408/0-szorty-adidas-entrada-14-short-f50636.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Essentials Logo Hoodie Grey', 'Męskie', 'Adidas', 'Adidas Essentials Logo Hoodie Grey to bluza sportowa, która została wykonana z wysokiej jakości baweły i poliestru. Bluza występuje w szarym kolorze z granatowymi elementami. Model posiada kaptur oraz przednią kieszeń, czyniąc ją idealną do codziennego użytku.', 139.99, 'Bluza', 'https://blob.sxv.pl/shops/media/f1000/2018/adidas/95439/ess-logo-po-b-b45729-5a69a68315d79.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Z.N.E. Pants Black', 'Męskie', 'Adidas', 'Spodnie sportowe adidas Z.N.E. Pants Black zostały zaprojektowane w kolorze czarnym. Produkt wykonany jest z najwyższej jakości materiałów tekstylnych oraz syntetycznych. Spodnie zostały zaprojektowana do codziennego użytku oraz ogólnej aktywności fizycznej.', 164.88, 'Spodnie', 'https://blob.sxv.pl/shops/media/f1000/2017/adidas/89895/zne-pant-2-br6816-59a55c9a494eb.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Reebok Workout Ready Compression Black', 'Męskie', 'Reebok', 'Koszulka kompresyjna Reebok Workout Ready Compression Black', 89.99, 'Kosulka', 'https://blob.sxv.pl/shops/media/f1000/2017/reebok/88081/koszulka-wor-compr-lo-sleeve-black-bk4180-5db161d8928d2.jpg.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas 3-Stripes Club Tee', 'Męskie', 'Adidas', 'Koszulka sportowa adidas 3-Stripes Club Tee', 84.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2019/adidas/149663/club-3str-tee-du0859-5d1c93048b44d.jpg');
-- damska
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Koszulka adidas reprezentacji Polski', 'Damskie', 'Adidas', 'Oficjalna meczowa koszulka reprezentacji polskich siatkarek należąca do aktualnej kolekcji kadrowej. Koszulka została wykonana w białym kolorze z czerwonymi elementami. Jej wyjątkowy charakter podkreśla zamieszczona na lewej piersi flaga Polski. Koszulka jest niezwykle dopasowana, wykonana z materiału gwarantującego wentylację na najwyższym poziomie. Panele boczne, pokryte specjalną siateczką przepuszczającą powietrze, zwiększają komfort podczas wysiłku. Warto podkreślić, iż jako jedyni w Polsce mamy możliwość nanoszenia na koszulki najnowszego wzoru numerów z logotypem "Polskiej Siatkówki" w postaci Orła. Prawdziwa gratka dla największych fanek biało-czerwonych.', 179.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2017/adidas/89540/koszulka-adidas-pzps-biaa-s98570-b-59e5f84d24696.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Koszulka adidas Mivball Cap J', 'Damskie', 'Adidas', 'Oficjalna koszulka meczowa reprezentacji polskich siatkarek. W tym modelu polskie zawodniczki występowały w Mistrzostwach Europy rozgrywanych w Belgii i Holandii w 2015 r. Prawdziwa gratka dla sympatyków i kibiców polskiej siatkówki. Koszulka wyposażona w system climacool, który zapewnia doskonałą wentylację podczas użytkowania. Produkt wykonany w 100% z włókien poliestrowych.', 159.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2014/adidas/45219/0-koszulka-adidas-mivball-cap-j-f82171-czerwona.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Koszulka adidas ESS 3S Tee', 'Damskie', 'Adidas', 'Koszulka adidas ESS 3S Tee to koszulka treningowa wchodząca w skład kolekcji adidas reprezentacji polskich siatkarek. Koszulka została zaprojektowana w kolorze szarym z białymi oraz czerwonymi elementami. Wzbogacona została o widoczną flagę polski wraz z logotypami sponsorów kadry Polski. Koszulka wykonana została z najwyższej jakości materiałów tekstylnych oraz syntetycznych. Produkt przeznaczony jest do treningu oraz ogólnej aktywności fizycznej. Może posłużyć również jako koszulka, w której będziesz wspierał polskich siatkarzy.', 9.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2013/adidas/26152/0-koszulka-adidas-x20824.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Mizuno Premium Womens Cap Sleeve', 'Damskie', 'Mizuno', 'Koszulka japońskiego producenta odzieży sportowej przeznaczona dla kobiet uprawiających siatkówkę. Wysokiej jakości koszulka, która sprawi Tobie jeszcze większą przyjemność z gry.', 39.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2016/mizuno/63542/56d44a1a2e936-koszulka-mizuno-premium-womens-cap-sleeve-v2ea470171.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Essentials Linear Tights', 'Damskie', 'Adidas', 'Leginsy sportowe adidas Essentials Linear Tights.', 89.99, 'Legginsy', 'https://blob.sxv.pl/shops/media/f1000/2019/adidas/149479/w-e-lin-tight-dp2386-5c4acdf518e1c.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Originals Trefoil', 'Damskie', 'Adidas', 'Bluza sportowa adidas Originals Trefoil', 199.99, 'Bluza', 'https://blob.sxv.pl/shops/media/f1000/2019/adidas/149487/trf-crew-sweat-dv2612-5c49b941a4eab.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas ESS MF TIGHT', 'Damskie', 'Adidas', 'Spodenki adidas ESS MF TIGHT dopasowują się do sylwetki jednocześnie nie krępując i nie ograniczając ruchów. Szerszy elastyczny pas utrzymuje spodenki na miejscu i zapobiega ich przesuwaniu.', 59.99, 'Spodenki', 'https://blob.sxv.pl/shops/media/f1000/2019/inne/149328/damskie-spodenki-v35290-5c333ca003a86.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas ID Stadium Pants Stadium Heather', 'Damskie', 'Adidas', 'Spodnie dresowe adidas ID Stadium Pants Stadium Heather.', 146.99, 'Spodnie', 'https://blob.sxv.pl/shops/media/f1000/2018/adidas/95765/spodnie-adidas-w-id-stadium-pt-cf0337-5a69f162bb30e.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Heartracer Jacker', 'Damskie', 'Adidas', 'Bluza adidas Heartracer Jacker została zaprojektowana w kolorze szarym. Wykonana została z miękkiej tkaniny o podwójnym splocie.  Bluza posiada suwak na całej długości, który ułatwia zakładanie oraz ściąganie. Produkt posiada dwie kieszenie boczne przeznaczone do przechowywania drobnych przedmiotów. Bluza adidas Heratracker Jacker przeznaczona jest do codziennego użytkowania.', 164.99, 'Bluza', 'https://blob.sxv.pl/shops/media/f1000/2019/adidas/150122/w-htr-jkt-cz2914-5c49c10df379f.jpg');
INSERT INTO clothes(name, gender, brand, description, prize, type, image) values('Adidas Trefoil Black', 'Damskie', 'Adidas', 'Koszulka sportowa adidas Trefoil Black.', 99.99, 'Koszulka', 'https://blob.sxv.pl/shops/media/f1000/2018/adidas/95792/koszulka-adidas-trefoil-cv9888-5cc048f386f36.jpg');

-- Akcesoria
-- piłki
INSERT INTO accessories(name, gender, brand, description, prize, type, image) values('Piłka Mikasa V200W', 'Dowolne', 'Mikasa', 'Piłka Mikasa V200W to najnowszy model oficjalnej piłki do siatkówki halowej. Model pojawił się w miejsce zasłużonej piłki Mikasa MVA200.  Mikasa V200W posiada doskonale wyważoną konstrukcję zbudowaną z 18 paneli. Sposób jej wykonania poprawia ruch piłki oraz gwarantuje zawodnikom większą kontrolę podczas gry. Piłka zbudowana została z żółto-niebieskich paneli o perforowanej strukturze. Mikro-wgłębienia zwiększają przyczepność piłki do dłoni. Ponadto żółte panele zostały wykonane w sposób zapobiegający śliskości powierzchni piłki podczas gry. Model V200W będzie uczestniczył w największych imprezach siatkarskich.', 259.99, 'Piłka', 'https://blob.sxv.pl/shops/media/f1000/2019/mikasa/160561/pilka-mikasa-v200w-5cf8fed221f5f.jpg');
-- plecaki i torby
INSERT INTO accessories(name, gender, brand, description, prize, type, image) values('Adidas Teambag', 'Dowolne', 'Adidas', 'Oficjalna torba z Mistrzostw Świata z 2014 r. w Polsce. Wielka gratka dla sympatyków siatkówki oraz osób ceniących oryginalne wzornictwo i znakomitą jakość. Torba posiada kieszenie zapinane na suwak oraz regulowany pasek, który ułatwia podróżowanie.', 69.99, 'Torba', 'https://blob.sxv.pl/shops/media/f1000/2015/adidas/59474/teambag-aa70011-56693f7dd5b06.jpg');
-- nakolanniki
INSERT INTO accessories(name, gender, brand, description, prize, type, image) values('Asics Gel-Kneepad', 'Dowolne', 'Asics', 'Nakolanniki produkcji asics stanowią świetne zabezpieczenie stawów kolanowych. Ich zadaniem jest ochrona kolan przed niechcianymi stłuczeniami, siniakami. Nakolanniki pokryte są białym kolorem. Posiadają mały logotyp firmy umieszczony na przedniej części ochraniaczy. Model został wzbogacony o wkładki Gel, które dodatkowo absorbują wstrząsy powstałe podczas kontaktu kolan z parkietem. ', 59.99, 'Nakolanniki', 'https://blob.sxv.pl/shops/media/f1000/2017/asics/89413/asics-gel-kneepad-146815-0001-5d7f6ded1f494.jpg');
-- rękawki siatkarskie
INSERT INTO accessories(name, gender, brand, description, prize, type, image) values('Rękawki siatkarskie Mizuno męskie', 'Męskie', 'Mizuno', 'Męskie rękawki Mizuno zaprojektowane w kolorze białym z czarnym logotypem japońskiego producenta sprzętu sportowego. Rękawki zostały wykonane z elastycznego materiału, który dopasowuje się do kształtu ramion. Zadaniem rękawków jest utrzymanie temperatury ciała zapewniając jednocześnie najwyższy komfort podczas gry.', 39.99, 'Rękawki siatkarskie', 'https://blob.sxv.pl/shops/media/f1000/2018/mizuno/105291/rekawki-siatkarskie-mizuno-aw18-32ey655301-5ba241ec34949.jpg');
-- skarpetki
INSERT INTO accessories(name, gender, brand, description, prize, type, image) values('Nike 3PPK Value Cotton Crew', 'Dowolne', 'Nike', 'Skarpety Nike 3PPK Value Cotton Crew to męskie skarpety sportowe zaprojektowane w kolorze białym z czarnym logotypem producenta. Skarpety świetnie nadają się do codziennego użytkowania oraz ogólnej aktywności fizycznej.', 44.99, 'Skarpetki', 'https://blob.sxv.pl/shops/media/f1000/2012/nike/17062/skarpety-nike-3ppk-value-cotton-crew-sx4508-101-5cbc24eeb34d2.jpg');
-- sprzęt do ćwiczeń
INSERT INTO accessories(name, gender, brand, description, prize, type, image) values('Multiband Blackroll', 'Dowolne', 'Multiband', 'Multiband Blackroll to specjalna taśma do cwiczeń zaprojektowana w kolorze zielonym. Jest przeznaczona do treningu funkcjonalnego w niskich oraz wysokich pozycjach.', 179.99, 'Sprzęt do ćwiczeń', 'https://blob.sxv.pl/shops/media/f1000/2019/blackroll/155035/tasma-blackroll-multi-band-multiband-5c5d91b3ee9a4.png');
-- inne
INSERT INTO accessories(name, gender, brand, description, prize, type, image) values('Adidas Baseball Classic Trefoil Cap', 'Dowolne', 'Adidas', 'Czapka z daszkiem adidas Baseball Classic Trefoil Cap', 59.99, 'Inne', 'https://blob.sxv.pl/shops/media/f1000/2019/adidas/149476/baseb-class-tre-dv0174-5c40546709392.jpg');

-- Suplementy
INSERT INTO supplements(name, brand, description, prize, type, image) values('Żel energetyczny Squeezy 33G - saszetka', 'Squeezy', 'SQUEEZY jest pierwszym na świecie dostawcą energii w żelu oraz optymalnym wyborem dla sportowców poszukujących najwyższej wydajności. Wszystkie produkty SQUEEZY są produkowane bez zbędnych składników. Dlatego żele energetyczne Squeezy są lekkostrawne i nie do pobicia w poszukiwaniu maksymalnej wydajności. Smak: brzoskwinia/pomarańcza', 6.99, 'Żel energetyczny', 'https://blob.sxv.pl/shops/media/f1000/2014/squeezy/49143/zel-energetyczny-squeezy-33g-brzoskwinia-pomarancza-squeezy-zel-brzo-pom-5a9f897d92ee5.jpg');
INSERT INTO supplements(name, brand, description, prize, type, image) values('PowerGym Energy Plus 1100 G', 'PowerGym', 'ENERGYPLUS to skoncentrowane źródło węglowodanów o niskim indeksie glikemicznym. Spożywając ENERGYPLUS przed rozpoczęciem ćwiczeń, uzupełnimy zapasy glikogenu, a tym samym będziemy mieli większą ilość „paliwa”, dzięki czemu zwiększy się nasza wydolność i zużyjemy więcej tłuszczu. Jest to możliwe, ponieważ ENERGYPLUS dostarcza nam węglowodanów o niskim indeksie glikemicznym. Ponadto ENERGY PLUS zawiera aminokwasy takie jak, tauryna, L-glutamina, L-arginina i L-tyrozyna, które poprawiają spalanie tłuszczu podczas wysiłku fizycznego (oszczędzając jednocześnie nasze zapasy glikogenu), zwiększają naszą wytrzymałość i redukują zmęczenie.', 139.99, 'Energy plus', 'https://blob.sxv.pl/shops/media/f1000/2014/powergym/44347/0-powergym-energy-plus-1100g-215988.jpg');